name: string_processor
version: 2.0.1
description: Utilities for processing strings, such as getting the best match with configurable options
author: Neel Kamath <neelkamath@icloud.com>
homepage: https://github.com/neelkamath/string-processor

dev_dependencies:
  link_checker: ^2.0.1
  test: ^1.5.3

environment:
  sdk: '>=2.1.0 <3.0.0'
